"""first

Revision ID: 4b75ce71c23a
Revises: 
Create Date: 2026-06-11 13:03:18.049108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b75ce71c23a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_locations_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_locations_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_city', 'locations', ['city'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('venue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending_approval', 'rejected', 'suspended', name='venuestatus'), server_default='pending_approval', nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_venues_capacity_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['venue_categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venues_category_id', 'venues', ['category_id'], unique=False)
    op.create_index('ix_venues_category_status', 'venues', ['category_id', 'status'], unique=False)
    op.create_index('ix_venues_location_id', 'venues', ['location_id'], unique=False)
    op.create_index('ix_venues_location_status', 'venues', ['location_id', 'status'], unique=False)
    op.create_index('ix_venues_owner_id', 'venues', ['owner_id'], unique=False)
    op.create_index('ix_venues_status', 'venues', ['status'], unique=False)
    op.create_table('venue_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venue_images_venue_id', 'venue_images', ['venue_id'], unique=False)
    op.create_index('ix_venue_images_venue_sort', 'venue_images', ['venue_id', 'sort_order'], unique=False)
    op.create_table('venue_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_venue_slots_time_range'),
    sa.CheckConstraint('price >= 0', name='ck_venue_slots_price'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'slot_date', 'start_time', 'end_time', name='uq_venue_slot')
    )
    op.create_index('ix_venue_slots_booking_search', 'venue_slots', ['venue_id', 'slot_date', 'is_available'], unique=False)
    op.create_index('ix_venue_slots_venue_date', 'venue_slots', ['venue_id', 'slot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venue_slots_venue_date', table_name='venue_slots')
    op.drop_index('ix_venue_slots_booking_search', table_name='venue_slots')
    op.drop_table('venue_slots')
    op.drop_index('ix_venue_images_venue_sort', table_name='venue_images')
    op.drop_index('ix_venue_images_venue_id', table_name='venue_images')
    op.drop_table('venue_images')
    op.drop_index('ix_venues_status', table_name='venues')
    op.drop_index('ix_venues_owner_id', table_name='venues')
    op.drop_index('ix_venues_location_status', table_name='venues')
    op.drop_index('ix_venues_location_id', table_name='venues')
    op.drop_index('ix_venues_category_status', table_name='venues')
    op.drop_index('ix_venues_category_id', table_name='venues')
    op.drop_table('venues')
    op.drop_table('venue_categories')
    op.drop_table('users')
    op.drop_index('ix_locations_city', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
